############################################################
# Dockerfile to build base OS to be referred later
FROM armhf/[current.repository][current.tag]
###########################################################
# File Author / Maintainer
MAINTAINER [user.name] "[user.email]"
################## BEGIN INSTALLATION ######################
RUN apk info
