############################################################
# Dockerfile to build base OS to be referred later
FROM [current.repository][current.tag]
###########################################################
# File Author / Maintainer
MAINTAINER [user.name] "[user.email]"
################## BEGIN INSTALLATION ######################
ENV DEBIAN_FRONTEND "noninteractive"
