############################################################
# Dockerfile to build base OS to be referred later
FROM armhfbuild/[current.repository][current.tag]

###########################################################
# File Author / Maintainer
MAINTAINER [user.name] "[user.id]"
################## BEGIN INSTALLATION ######################
ENV DEBIAN_FRONTEND "noninteractive"
RUN /bin/bash -c "apt-get update && apt-get upgrade -y && apt-get clean && apt-get autoremove"
